version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-doc-assist-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Wenn Nginx im Frontend proxyt, sind CORS-Header hier nicht nötig.
      # - CORS_ALLOWED_ORIGIN=http://localhost:4200,http://frontend
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-3.5-turbo
      - JAVA_OPTS=-Xmx1024m -Xms512m
      - SERVER_PORT=8080
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_BITS=DEBUG
    volumes:
      - ./backend/logs:/app/logs
      - backend-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-doc-assist-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      # Angular verwendet in PROD `apiUrl: /api` (siehe environment.prod.ts).
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

  # Optional: Postgres (auskommentiert)
  # database:
  #   image: postgres:15-alpine
  #   container_name: ai-doc-assist-db
  #   environment:
  #     - POSTGRES_DB=aidocassist
  #     - POSTGRES_USER=aidocassist
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network

volumes:
  backend-data:
    driver: local
  # postgres-data:
  #   driver: local

networks:
  app-network:
    name: ai-doc-assist-network
    driver: bridge
